const mongoose = require("mongoose");
const {Schema} = mongoose;

const characterSchema = new mongoose.Schema({
    characterName: String,
    charClass: [{ type: Schema.Types.ObjectId, ref: 'Class' }],
    subclass: String,
    level: String,
    race: String,
    subrace: String,
    background: String,
    alignment: String,
    experience: String,
    playerName: String,
    strength: String,
    dexterity: String,
    constitution: String,
    intelligence: String,
    wisdom: String,
    charisma: String,
    armorClass: String,
    initiative: String,
    speed: String,
    acrobatics: String,
    animalHandling: String,
    arcana: String,
    athletics: String,
    deception: String,
    history: String,
    insight: String,
    intimidation: String,
    investigation: String,
    medicine: String,
    nature: String,
    perception: String,
    performance: String,
    persuasion: String,
    religion: String,
    sleightOfHand: String,
    stealth: String,
    survival: String,
    spell: String,
    maxHitPoints: String,
    strThrow: String,
    dexThrow: String,
    conThrow: String,
    intThrow: String,
    wisThrow: String,
    chaThrow: String,
    darkVision: String,
    equipment: String,
    personalityTraits: String,
    ideals: String,
    bonds: String,
    flaws: String,
    featsTraits: String,
})

module.exports = mongoose.model('Characters', characterSchema)